#!/bin/bash
# Kairo Phantom — macOS/Linux Installer
# Usage: curl -sSL https://raw.githubusercontent.com/your-org/kairo-phantom/main/install.sh | bash

set -euo pipefail

KAIRO_VERSION="0.3.0"
INSTALL_DIR="$HOME/.kairo-phantom"
BIN_DIR="$HOME/.local/bin"
CONFIG_DIR="$INSTALL_DIR"
PLUGINS_DIR="$INSTALL_DIR/plugins"

# ── Colors ─────────────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
BLUE='\033[0;34m'; CYAN='\033[0;36m'; BOLD='\033[1m'; RESET='\033[0m'

header() { echo -e "\n${BOLD}${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"; echo -e "${BOLD}${CYAN}  $1${RESET}"; echo -e "${BOLD}${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}\n"; }
ok()     { echo -e "  ${GREEN}✓${RESET} $1"; }
warn()   { echo -e "  ${YELLOW}⚠${RESET}  $1"; }
fail()   { echo -e "  ${RED}✗${RESET} $1"; exit 1; }
step()   { echo -e "  ${BLUE}→${RESET} $1"; }

header "Kairo Phantom v${KAIRO_VERSION} Installer"
echo -e "  The AI ghost-writer that works in ANY app."
echo -e "  Hotkey: Alt+M | Read context | Stream AI | Ghost type\n"

# ── Detect OS ─────────────────────────────────────────────────────────────────
OS="$(uname -s)"
ARCH="$(uname -m)"

case "$OS" in
  Darwin) PLATFORM="macos" ;;
  Linux)  PLATFORM="linux" ;;
  *)      fail "Unsupported OS: $OS. Use install.ps1 on Windows." ;;
esac

step "Detected: $OS / $ARCH / $PLATFORM"

# ── Check Rust ────────────────────────────────────────────────────────────────
step "Checking Rust toolchain..."
if ! command -v cargo &>/dev/null; then
  step "Installing Rust via rustup..."
  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --no-modify-path
  source "$HOME/.cargo/env"
fi
RUST_VER=$(rustc --version 2>/dev/null || echo "none")
ok "Rust: $RUST_VER"

# ── Check Python ──────────────────────────────────────────────────────────────
step "Checking Python..."
if command -v python3 &>/dev/null; then
  PYTHON_CMD="python3"
elif command -v python &>/dev/null; then
  PYTHON_CMD="python"
else
  fail "Python not found. Install Python 3.10+ from https://python.org"
fi
PYTHON_VER=$($PYTHON_CMD --version 2>&1)
ok "Python: $PYTHON_VER"

# ── Install Python deps ───────────────────────────────────────────────────────
step "Installing Python dependencies..."
$PYTHON_CMD -m pip install --upgrade --quiet python-pptx pillow requests 2>/dev/null || \
  warn "pip install failed — run manually: pip install python-pptx pillow requests"
ok "Python deps installed"

# ── Create directories ────────────────────────────────────────────────────────
step "Creating installation directories..."
mkdir -p "$INSTALL_DIR" "$PLUGINS_DIR" "$BIN_DIR"
ok "Directories: $INSTALL_DIR"

# ── Write default config ──────────────────────────────────────────────────────
CONFIG_FILE="$CONFIG_DIR/config.toml"
if [ ! -f "$CONFIG_FILE" ]; then
  step "Writing default config..."
  cat > "$CONFIG_FILE" << 'TOML'
# Kairo Phantom Configuration
# Generated by install.sh

[kairo]
version = "0.3.0"
hotkey = "AltM"
log_level = "info"

[ai]
# Set your preferred AI backend
# Option 1: OpenAI (cloud, best quality)
# openai_api_key = "sk-..."
# model = "gpt-4o"

# Option 2: Gemini (cloud, Google)
# gemini_api_key = "AIza..."
# model = "gemini-2.0-flash"

# Option 3: Ollama (local, private)
ollama_base_url = "http://localhost:11434"
model = "llama3.2"

[image]
# Image generation backend
# openai_api_key = "sk-..." for gpt-image-1
# gemini_api_key = "AIza..." for Imagen 3
ollama_base_url = "http://localhost:11434"
offline_only = false

[swarm]
enabled = true
# brain: the LLM that routes to the right agent
# brain_api_key = "sk-..."

[mcp]
# For Canva Connect integration
# canva_access_token = "..."
TOML
  ok "Config: $CONFIG_FILE"
fi

# ── Build from source ─────────────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

if [ -f "$SCRIPT_DIR/phantom-core/Cargo.toml" ]; then
  step "Building Kairo Phantom from source..."
  cd "$SCRIPT_DIR"
  cargo build --release --manifest-path phantom-core/Cargo.toml 2>&1 | tail -5
  
  BINARY="$SCRIPT_DIR/target/release/kairo-phantom"
  if [ -f "$BINARY" ]; then
    cp "$BINARY" "$BIN_DIR/kairo-phantom"
    ok "Binary installed: $BIN_DIR/kairo-phantom"
  else
    warn "Binary not found at $BINARY — build may have failed"
  fi

  # Install kairo-mcp
  if [ -f "$SCRIPT_DIR/mcp-servers/kairo-mcp/Cargo.toml" ]; then
    cargo build --release --manifest-path mcp-servers/kairo-mcp/Cargo.toml 2>&1 | tail -3
    MCP_BIN="$SCRIPT_DIR/target/release/kairo-mcp"
    [ -f "$MCP_BIN" ] && cp "$MCP_BIN" "$BIN_DIR/kairo-mcp" && ok "MCP server: $BIN_DIR/kairo-mcp"
  fi
else
  step "Downloading pre-built binary..."
  RELEASE_URL="https://github.com/your-org/kairo-phantom/releases/download/v${KAIRO_VERSION}"
  BINARY_NAME="kairo-phantom-${PLATFORM}-${ARCH}"
  curl -sL "$RELEASE_URL/$BINARY_NAME" -o "$BIN_DIR/kairo-phantom" || warn "Download failed — build from source"
  chmod +x "$BIN_DIR/kairo-phantom"
fi

# ── Install plugins ───────────────────────────────────────────────────────────
step "Installing hero plugins..."
if [ -d "$SCRIPT_DIR/plugins" ]; then
  cp "$SCRIPT_DIR/plugins/"*.toml "$PLUGINS_DIR/" 2>/dev/null || true
  PLUGIN_COUNT=$(ls "$PLUGINS_DIR"/*.toml 2>/dev/null | wc -l | tr -d ' ')
  ok "$PLUGIN_COUNT plugins installed in $PLUGINS_DIR"
fi

# ── Install MCP bridge scripts ────────────────────────────────────────────────
MCP_DIR="$INSTALL_DIR/mcp-servers"
mkdir -p "$MCP_DIR/office-pptx-bridge" "$MCP_DIR/figma-bridge"
if [ -d "$SCRIPT_DIR/mcp-servers" ]; then
  cp -r "$SCRIPT_DIR/mcp-servers/." "$MCP_DIR/" 2>/dev/null || true
  ok "MCP bridge scripts: $MCP_DIR"
fi

# ── Shell PATH ────────────────────────────────────────────────────────────────
SHELL_RC=""
if [ -f "$HOME/.zshrc" ]; then
  SHELL_RC="$HOME/.zshrc"
elif [ -f "$HOME/.bashrc" ]; then
  SHELL_RC="$HOME/.bashrc"
fi

PATH_LINE="export PATH=\"\$HOME/.local/bin:\$PATH\""
if [ -n "$SHELL_RC" ] && ! grep -q ".local/bin" "$SHELL_RC" 2>/dev/null; then
  echo "$PATH_LINE" >> "$SHELL_RC"
  ok "Added $BIN_DIR to PATH in $SHELL_RC"
fi

# ── Ollama check ──────────────────────────────────────────────────────────────
step "Checking Ollama (optional local AI)..."
if command -v ollama &>/dev/null; then
  ok "Ollama found: $(ollama --version 2>/dev/null || echo 'installed')"
else
  warn "Ollama not found — install from https://ollama.ai for offline mode"
  warn "After install: ollama pull llama3.2"
fi

# ── macOS accessibility ───────────────────────────────────────────────────────
if [ "$PLATFORM" = "macos" ]; then
  echo ""
  warn "macOS: Grant Accessibility access in System Settings → Privacy → Accessibility"
  warn "Add 'kairo-phantom' to the allowed apps list."
fi

# ── Done ──────────────────────────────────────────────────────────────────────
header "Installation Complete!"
echo -e "  ${BOLD}Start Kairo:${RESET}  kairo-phantom"
echo -e "  ${BOLD}Hotkey:${RESET}       Alt+M (anywhere!)"
echo -e "  ${BOLD}Config:${RESET}       $CONFIG_FILE"
echo -e "  ${BOLD}Plugins:${RESET}      $PLUGINS_DIR"
echo ""
echo -e "  ${BOLD}Next steps:${RESET}"
echo -e "  1. Add your API key to $CONFIG_FILE"
echo -e "     → OpenAI:  openai_api_key = \"sk-...\""
echo -e "     → Gemini:  gemini_api_key = \"AIza...\""
echo -e "     → Or use Ollama (offline, already configured)"
echo ""
echo -e "  2. Open any document (Word, Google Docs, Notion, VS Code...)"
echo -e "  3. Press Alt+M, type your request, press Enter"
echo -e "  4. Watch Kairo write ✨"
echo ""
echo -e "  ${CYAN}Documentation: https://github.com/your-org/kairo-phantom${RESET}"
echo ""
