#!/usr/bin/env python3
"""
install.py — Kairo Phantom one-liner setup for Windows, macOS, Linux.
Checks for Rust, installs kairo-phantom, verifies Ollama, and creates default config.
"""

import subprocess, sys, os, platform

OS = platform.system()
ARCH = platform.machine()

BANNER = r"""
  ██╗  ██╗ █████╗ ██╗██████╗  ██████╗ 
  ██║ ██╔╝██╔══██╗██║██╔══██╗██╔═══██╗
  █████╔╝ ███████║██║██████╔╝██║   ██║
  ██╔═██╗ ██╔══██║██║██╔══██╗██║   ██║
  ██║  ██╗██║  ██║██║██║  ██║╚██████╔╝
  ╚═╝  ╚═╝╚═╝  ╚═╝╚═╝╚═╝  ╚═╝ ╚═════╝ 
  PHANTOM — Universal Document Copilot
"""

def run(cmd: str, check=True) -> str:
    result = subprocess.run(cmd, shell=True, capture_output=True, text=True)
    if check and result.returncode != 0:
        raise RuntimeError(f"Command failed: {cmd}\n{result.stderr}")
    return result.stdout.strip()

def check_rust():
    try:
        v = run("cargo --version", check=False)
        print(f"✅ Rust found: {v}")
        return True
    except:
        print("⚠️  Rust not found.")
        if OS == "Windows":
            print("   Install Rust: https://rustup.rs/")
            print("   Or run: winget install Rustlang.Rustup")
        elif OS == "Darwin":
            print("   Install Rust: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh")
        else:
            print("   Install Rust: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh")
        return False

def check_ollama():
    try:
        import urllib.request
        urllib.request.urlopen("http://localhost:11434/api/tags", timeout=3)
        print("✅ Ollama is running (offline mode available)")
        return True
    except:
        print("⚠️  Ollama not detected (optional for cloud mode)")
        if OS == "Windows":
            print("   Install: winget install Ollama.Ollama")
        elif OS == "Darwin":
            print("   Install: brew install ollama")
        else:
            print("   Install: curl -fsSL https://ollama.ai/install.sh | sh")
        print("   Then: ollama pull qwen2.5-coder:14b")
        return False

def install_kairo():
    print("\n🔨 Building kairo-phantom...")
    run("cargo install --path phantom-core")
    print("✅ kairo-phantom installed!")

def create_default_config():
    home = os.path.expanduser("~")
    config_dir = os.path.join(home, ".kairo-phantom")
    os.makedirs(config_dir, exist_ok=True)
    config_path = os.path.join(config_dir, "config.toml")
    
    if not os.path.exists(config_path):
        config = '''# Kairo Phantom Configuration
# Generated by install.py

[model]
provider = "ollama"
model_name = "qwen2.5-coder:14b"

# Uncomment to use OpenAI (cloud mode):
# [model]
# provider = "openai"
# api_key = "sk-..."
# model_name = "gpt-4o"

[image_generation]
offline_only = false
image_size = "1024x1024"
image_quality = "standard"

[yjs]
enabled = false
auto_detect = true

[hotkey]
key = "m"
alt = true
ctrl = true
shift = false

typing_delay_ms = 0
'''
        with open(config_path, "w") as f:
            f.write(config)
        print(f"✅ Default config created: {config_path}")
    else:
        print(f"ℹ️  Config already exists: {config_path}")

def main():
    print(BANNER)
    print(f"🚀 Kairo Phantom Installer ({OS} {ARCH})")
    print("=" * 50)

    if not check_rust():
        print("\n❌ Please install Rust first, then re-run this script.")
        sys.exit(1)

    check_ollama()

    if "--skip-build" not in sys.argv:
        install_kairo()

    create_default_config()

    print("\n" + "=" * 50)
    print("🎉 Kairo Phantom is ready!")
    print("\nTo start:")
    print("  kairo-phantom")
    print("\nThen press Alt+Ctrl+M in any app to ghost-write!")
    print("\nFor MCP integration with Claude Code:")
    print("  cargo install --path mcp-servers/kairo-mcp")
    print("  Add to ~/.claude/mcp_settings.json:")
    print('  {"kairo": {"command": "kairo-mcp", "args": ["--stdio"]}}')
    print("\nDocs: https://github.com/your-org/kairo-phantom")

if __name__ == "__main__":
    main()
