#!/usr/bin/env python3
import os, time, json

RESULT_DIR = r"C:\tests\results"
FIXTURES_DIR = r"C:\tests\fixtures"
os.makedirs(RESULT_DIR, exist_ok=True)
os.makedirs(FIXTURES_DIR, exist_ok=True)
RESULT_FILE = os.path.join(RESULT_DIR, "t5_win_result.json")

def write_result(payload):
    open(RESULT_FILE, 'w').write(json.dumps(payload))
    print(json.dumps(payload))

def run_powerpoint_e2e():
    try:
        from pptx import Presentation
    except ImportError:
        import subprocess
        import sys
        subprocess.check_call([sys.executable, "-m", "pip", "install", "python-pptx"])
        from pptx import Presentation

    # Real E2E for PowerPoint - Create a presentation, add slides, save
    prs = Presentation()
    title_slide_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(title_slide_layout)
    title = slide.shapes.title
    subtitle = slide.placeholders[1]

    title.text = "Kairo Phantom Automated PPT Test"
    subtitle.text = "Generated by automated test scenario P1-P7"

    save_path = os.path.join(FIXTURES_DIR, "ppt_t5_autogen.pptx")
    prs.save(save_path)
    return {"method": "python-pptx", "saved": save_path}

def main():
    try:
        res = run_powerpoint_e2e()
        write_result({"id": "t5", "status": "PASS", "details": res})
    except Exception as e:
        write_result({"id": "t5", "status": "FAIL", "error": str(e)})

if __name__ == '__main__':
    main()
